# Generated by Django 5.1 on 2024-04-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='qty',
        ),
    ]
