# Generated by Django 5.1 on 2024-04-29 14:41

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_orders_user_id_orders_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status_id',
            field=models.ForeignKey(default=main.models.Status, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
    ]
