# Generated by Django 5.1 on 2024-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orders_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='Нfdgdf', max_length=255),
        ),
    ]
