# Generated by Django 5.1 on 2024-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.PositiveIntegerField(default=1, max_length=255),
        ),
    ]
